[env:cyobrain]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    adafruit/Adafruit NeoPixel@1.15.5
    bblanchon/ArduinoJson@6.21.5
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
monitor_speed = 115200
upload_speed = 460800
extra_scripts = pre:tools/wifi_config.py
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D CORE_DEBUG_LEVEL=0
    -I lib/esp_codec_dev/interface
    -I lib/esp_codec_dev/device/include
    -I lib/esp_codec_dev/device/priv_include
